//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelStory.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TravelStory.Resources.Dictionary", typeof(Dictionary).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creato.
        /// </summary>
        public static string AccountCreated {
            get {
                return ResourceManager.GetString("AccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profilo aggiornato.
        /// </summary>
        public static string AccountUpdated {
            get {
                return ResourceManager.GetString("AccountUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi file media.
        /// </summary>
        public static string AddMedia {
            get {
                return ResourceManager.GetString("AddMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi Photo.
        /// </summary>
        public static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi Video.
        /// </summary>
        public static string AddVideo {
            get {
                return ResourceManager.GetString("AddVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allerta.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota errata.
        /// </summary>
        public static string AlertErrMex {
            get {
                return ResourceManager.GetString("AlertErrMex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username e/o Password errati.
        /// </summary>
        public static string AlertErrMexLogin {
            get {
                return ResourceManager.GetString("AlertErrMexLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alle.
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indietro.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancella.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi.
        /// </summary>
        public static string CloseTravel {
            get {
                return ResourceManager.GetString("CloseTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creazione account...
        /// </summary>
        public static string CreatingAccount {
            get {
                return ResourceManager.GetString("CreatingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viaggio Attuale.
        /// </summary>
        public static string CurrTravel {
            get {
                return ResourceManager.GetString("CurrTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato data.
        /// </summary>
        public static string DateFormatPickerTitle {
            get {
                return ResourceManager.GetString("DateFormatPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dal:.
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al:.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcola indirizzi.
        /// </summary>
        public static string DecodeAdd {
            get {
                return ResourceManager.GetString("DecodeAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina Video.
        /// </summary>
        public static string DeleteVideo {
            get {
                return ResourceManager.GetString("DeleteVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina Foto.
        /// </summary>
        public static string delPhoto {
            get {
                return ResourceManager.GetString("delPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dettaglio.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dettaglio Media.
        /// </summary>
        public static string DetailMedia {
            get {
                return ResourceManager.GetString("DetailMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica info.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica titolo.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica viaggio.
        /// </summary>
        public static string EditTravel {
            get {
                return ResourceManager.GetString("EditTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concludi Viaggio.
        /// </summary>
        public static string EndTravel {
            get {
                return ResourceManager.GetString("EndTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La prima posizione non si può cancellare!.
        /// </summary>
        public static string ErrFirstMedia {
            get {
                return ResourceManager.GetString("ErrFirstMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato errato!.
        /// </summary>
        public static string ErrNewTitle {
            get {
                return ResourceManager.GetString("ErrNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La vecchia password non corrisponde.
        /// </summary>
        public static string ErrorOldPsWMatch {
            get {
                return ResourceManager.GetString("ErrorOldPsWMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uscita.
        /// </summary>
        public static string ExitApp {
            get {
                return ResourceManager.GetString("ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generali.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ottieni Posizione.
        /// </summary>
        public static string GetPosition {
            get {
                return ResourceManager.GetString("GetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizzazione in corso...
        /// </summary>
        public static string GettingPos {
            get {
                return ResourceManager.GetString("GettingPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;applicazione vuole cambiare le seguenti impostazioni:@@Usare GPS, Wi-Fi e reti mobili per la localizzazione.
        /// </summary>
        public static string GPSMex {
            get {
                return ResourceManager.GetString("GPSMex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titolo del viaggio.
        /// </summary>
        public static string HintTravelTitle {
            get {
                return ResourceManager.GetString("HintTravelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome completo.
        /// </summary>
        public static string HintUsername {
            get {
                return ResourceManager.GetString("HintUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email non valida.
        /// </summary>
        public static string IncEmail {
            get {
                return ResourceManager.GetString("IncEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completa tutti i campi obbligatori.
        /// </summary>
        public static string IncMandatory {
            get {
                return ResourceManager.GetString("IncMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password non corrispondenti.
        /// </summary>
        public static string IncPsw {
            get {
                return ResourceManager.GetString("IncPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa i bottoni in basso per aggiungere soste al tuo viaggio.
        /// </summary>
        public static string InfoEmptyTravel {
            get {
                return ResourceManager.GetString("InfoEmptyTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premere l&apos;immagine per aprire le opzioni..
        /// </summary>
        public static string InfoImage {
            get {
                return ResourceManager.GetString("InfoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione.
        /// </summary>
        public static string LabelDesc {
            get {
                return ResourceManager.GetString("LabelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingue.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lasciare vuoto per non cambiare password.
        /// </summary>
        public static string LeaveEntriesBlank {
            get {
                return ResourceManager.GetString("LeaveEntriesBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login effettuato con successo.
        /// </summary>
        public static string Loggedin {
            get {
                return ResourceManager.GetString("Loggedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login in corso...
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnetti utente.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campi obbligatori.
        /// </summary>
        public static string MandatoryEntries {
            get {
                return ResourceManager.GetString("MandatoryEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappa.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenuto.
        /// </summary>
        public static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuoi eliminare questo file?.
        /// </summary>
        public static string MexDelFile {
            get {
                return ResourceManager.GetString("MexDelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuoi eliminare questa sosta?.
        /// </summary>
        public static string MexDelMedia {
            get {
                return ResourceManager.GetString("MexDelMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuoi eliminare questo viaggio?.
        /// </summary>
        public static string MexDelTravel {
            get {
                return ResourceManager.GetString("MexDelTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuoi concludere questo viaggio?.
        /// </summary>
        public static string MexEndTravel {
            get {
                return ResourceManager.GetString("MexEndTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuoi effettuare il logout?.
        /// </summary>
        public static string MexLogout {
            get {
                return ResourceManager.GetString("MexLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuova password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ripeti la nuova password.
        /// </summary>
        public static string NewPasswordRepeat {
            get {
                return ResourceManager.GetString("NewPasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apri fotocamera.
        /// </summary>
        public static string newPhoto {
            get {
                return ResourceManager.GetString("newPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire il nuovo titolo....
        /// </summary>
        public static string NewTitle {
            get {
                return ResourceManager.GetString("NewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apri videocamera.
        /// </summary>
        public static string newVideo {
            get {
                return ResourceManager.GetString("newVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessuna connessione internet attiva..
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun contenuto è presente.
        /// </summary>
        public static string NoMedia {
            get {
                return ResourceManager.GetString("NoMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessuna sosta presente!.
        /// </summary>
        public static string NoStops {
            get {
                return ResourceManager.GetString("NoStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vecchia password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apri Foto.
        /// </summary>
        public static string openPhoto {
            get {
                return ResourceManager.GetString("openPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ripeti password.
        /// </summary>
        public static string PasswordRepeat {
            get {
                return ResourceManager.GetString("PasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scegli foto dalla galleria.
        /// </summary>
        public static string pickPhoto {
            get {
                return ResourceManager.GetString("pickPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scegli video dalla galleria.
        /// </summary>
        public static string pickVideo {
            get {
                return ResourceManager.GetString("pickVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riprodurre Video.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea nuovo account.
        /// </summary>
        public static string RegisterUser {
            get {
                return ResourceManager.GetString("RegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account già esistente.
        /// </summary>
        public static string SameAccount {
            get {
                return ResourceManager.GetString("SameAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva username.
        /// </summary>
        public static string SaveUsername {
            get {
                return ResourceManager.GetString("SaveUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricerca GPS in corso....
        /// </summary>
        public static string SearchingGPS {
            get {
                return ResourceManager.GetString("SearchingGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricerca titolo viaggio.
        /// </summary>
        public static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostazioni.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostra i filtri.
        /// </summary>
        public static string ShowFilters {
            get {
                return ResourceManager.GetString("ShowFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostra Percorso.
        /// </summary>
        public static string ShowPins {
            get {
                return ResourceManager.GetString("ShowPins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inizia Viaggio.
        /// </summary>
        public static string StartTravel {
            get {
                return ResourceManager.GetString("StartTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successo.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognome.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronizzazione effettuata.
        /// </summary>
        public static string SyncOK {
            get {
                return ResourceManager.GetString("SyncOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronizzazione in corso.
        /// </summary>
        public static string SyncOnGoing {
            get {
                return ResourceManager.GetString("SyncOnGoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronizzazione automatica:.
        /// </summary>
        public static string SyncText {
            get {
                return ResourceManager.GetString("SyncText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronizza online.
        /// </summary>
        public static string SyncTravls {
            get {
                return ResourceManager.GetString("SyncTravls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prendi una nota ....
        /// </summary>
        public static string TakeNote {
            get {
                return ResourceManager.GetString("TakeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prendi nota.
        /// </summary>
        public static string TakeNotePage {
            get {
                return ResourceManager.GetString("TakeNotePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inizia a scrivere una nota....
        /// </summary>
        public static string TakeNotePlaceholder {
            get {
                return ResourceManager.GetString("TakeNotePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        public static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string TakeVideo {
            get {
                return ResourceManager.GetString("TakeVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferma.
        /// </summary>
        public static string TitleConfMex {
            get {
                return ResourceManager.GetString("TitleConfMex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usare localizzazione?.
        /// </summary>
        public static string TitleGPSMex {
            get {
                return ResourceManager.GetString("TitleGPSMex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viaggio.
        /// </summary>
        public static string Travel {
            get {
                return ResourceManager.GetString("Travel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viaggi Conclusi.
        /// </summary>
        public static string Travels {
            get {
                return ResourceManager.GetString("Travels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiorna info.
        /// </summary>
        public static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiornando il profilo....
        /// </summary>
        public static string UpdatingAccount {
            get {
                return ResourceManager.GetString("UpdatingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avviso.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SI.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
